/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Game2048: typeof import('./src/components/User/Game2048.vue')['default']
    GameDetails: typeof import('./src/components/User/GameDetails.vue')['default']
    GameList: typeof import('./src/components/Admin/GameList.vue')['default']
    GameManage: typeof import('./src/components/Admin/GameManage.vue')['default']
    GameSnake: typeof import('./src/components/User/GameSnake.vue')['default']
    GoBang: typeof import('./src/components/User/GoBang.vue')['default']
    LeftTitle: typeof import('./src/components/Admin/LeftTitle.vue')['default']
    Login: typeof import('@/components/UserLogin.vue')['default']
    Rank: typeof import('./src/components/User/Rank.vue')['default']
    Register: typeof import('./src/components/Register.vue')['default']
    RightAside: typeof import('./src/components/Admin/RightAside.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchVue: typeof import('./src/components/SearchVue.vue')['default']
    Test: typeof import('./src/components/test.vue')['default']
    UserManage: typeof import('./src/components/Admin/UserManage.vue')['default']
    UserSuggestion: typeof import('./src/components/Admin/UserSuggestion.vue')['default']
  }
}
